name: Test Workflow

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/labeler.yaml

  create-deployment:
    name: Create Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Create Pending Deployment
        run: |
          sleep 5
          echo "Pending Deployment Created"

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: create-deployment
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build --if-present

  # linting:
  #   name: Super Lint
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2
  #       with:
  #         # Full git history is needed to get a proper list of changed files within `super-linter`
  #         fetch-depth: 0

  #     ################################
  #     # Run Linter against code base #
  #     ################################
  #     - name: Lint Code Base
  #       uses: github/super-linter@v4
  #       env:
  #         DEFAULT_BRANCH: master
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         VALIDATE_ALL_CODEBASE: false
  #         VALIDATE_GITHUB_ACTIONS: false

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    # needs: [integration-test, unit-test, linting]
    needs: [integration-test, unit-test]

    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: |
          docker build -t typescript-node-boilerplate:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'typescript-node-boilerplate:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          # format: 'template'
          # template: '@/contrib/sarif.tpl'
          # output: 'trivy-results.sarif'

      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: 'trivy-results.sarif'

  update-deployment:
    name: Update Deployment
    runs-on: ubuntu-latest
    # needs: [integration-test, unit-test, linting]
    # needs: [integration-test, unit-test]
    needs: build-image
    if: ${{ always() }}
    steps:
      - name: Update Deployment Status
        run: |
          sleep 5
          echo "Deployment Updated"
